name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - main
      - feat-*
      - beta-*
      - wip-*

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y wine32

      - name: Show working directory
        run: pwd

      - name: Fetch dependencies
        run: |
          curl -L https://github.com/gb-studio-dev/gbvm-test-deps/archive/refs/tags/v0.0.2.zip > deps.zip
          unzip deps.zip -d deps
          cd deps/gbvm-test-deps*/files
          mkdir /gbdk
          tar -xvzf gbdk-linux64.tar.gz -C /gbdk --strip-components=1
          unzip bgb.zip -d /bgb
          unzip gbspack*.zip -d /gbspack

      - name: Install / Run X Virtual Frame Buffer
        run: |
          sudo apt-get install xvfb
          Xvfb :0 -screen 0 1024x768x16 &

      - name: Install python dependencies
        run: |
          pip install pillow

      - name: Run Tests
        run: |
          make GBDK="/gbdk" GBSPACK="/gbspack/gbspack" EMU="DISPLAY=:0.0 wine /bgb/bgb.exe" test
